apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: comp-413-fbc-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: comp-413-fbc-test
    app.kubernetes.io/part-of: fbc-test
  name: comp-413-fbc-test
spec:
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    app.kubernetes.io/instance: comp-413-fbc-test
status:
  loadBalancer: {}
